export const POKEMON_TYPE_COLOR: any = {
  fire: "#f42",
  grass: "#7c5",
  electric: "#fc3",
  water: "#39f",
  ground: "#db5",
  rock: "#ba6",
  fairy: "#d97ce8",
  poison: "#a59",
  bug: "#7c5",
  dragon: "#76e",
  psychic: "#f59",
  flying: "#89f",
  fighting: "#b54",
  normal: "#aa9",
  ice: "#6cf",
  ghost: "#66b",
  dark: "#92400E99",
  steel: "rgba(152,151,151,0.6)",
};

export const POKEMON_TYPE: any = {
  fire: "fire",
  grass: "grass",
  electric: "electric",
  water: "water",
  ground: "ground",
  rock: "rock",
  fairy: "fairy",
  poison: "poison",
  bug: "bug",
  dragon: "dragon",
  psychic: "psychic",
  flying: "flying",
  fighting: "fighting",
  normal: "normal",
  ice: "ice",
  ghost: "ghost",
  dark: "dark",
  steel: "steel",
};
